-- Inicio carga de partidas
DELETE FROM BGN.PLAYPLAYERREL;
DELETE FROM BGN.PLAY;
DELETE FROM BGN.GAME WHERE OWNED = 0;
ALTER TABLE BGN.PLAY AUTO_INCREMENT = 1;
-- Fin carga de partidas

SELECT * FROM BGN.IMAGE where game_id = 13;

SELECT * FROM BGN.IMAGE where name like '%nueva%%';

INSERT INTO BGN.IMAGE(GAME_ID, NAME, SEQUENCE) VALUES (70, 'nuevaángeles3.jpg', 2);


SELECT MAX(ID) FROM BGN.IMAGE;

UPDATE BGN.IMAGE SET NAME = LOWER(NAME);